django13/django13/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favoritos.urls'))
]

django13/favoritos/urls.py
from django.urls import path

from .views import *

app_name = 'favoritos'

urlpatterns = [
    path('', index_favoritos, name='index'),
    path('crear', crear_favoritos, name='crear'),
    path('borrar/<int:pk>', borrar_favoritos, name='borrar'),
    path('detalle/<int:pk>', detalle_favoritos, name='detalle'),
    path('actualizar/<int:pk>', actualizar_favoritos, name='actualizar'),
]

django13/favoritos/models.py
from django.db import models

# Create your models here.
class Favoritos(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    url = models.URLField()

django13/favoritos/forms.py
from django import forms
from .models import Favoritos

class FavoritoForm(forms.Form):
    nombre = forms.CharField()
    url = forms.URLField()

class FavoritoModelForm(forms.ModelForm):
    class Meta:
        model = Favoritos
        fields = '__all__' # ['nombre']

django13/favoritos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Favoritos
#from .forms import FavoritoForm
from .forms import FavoritoModelForm

# Create your views here.
def index_favoritos(request):
    favoritos_lista = Favoritos.objects.all()
    
    #for fav in favoritos_lista:
    #    print(fav.nombre)
    #    print(fav.url)

    context = {
        'favoritos_lista':favoritos_lista
    }


    return render(request, 'favoritos/lista.html', context)

def crear_favoritos(request):

     # form = FavoritoForm()
    form = FavoritoModelForm()

    if request.method == 'POST':
        form = FavoritoModelForm(request.POST)

        if form.is_valid():
            form.save()
        else:
            print(form.errors)
        
        
        
        #print(request.POST)
        #nombre = request.POST['nombre']
        #url = request.POST['url']
       # form = FavoritoForm(request.POST)
        #if form.is_valid():
       #     nombre = form.cleaned_data['nombre']
       #     url = form.cleaned_data['url']
      #      Favoritos.objects.create(nombre=nombre, url=url)
       # else:
       #     print(form.errors)
        #favorito = Favoritos()
        #favorito.nombre = nombre
        #favorito.url = url
        #favorito.save()

    context = {
        'form':form,
        'titulo':'Crear favorito'
    }
    return render(request, 'favoritos/crear.html', context)



def borrar_favoritos(request, pk):
    Favoritos.objects.get(pk=pk).delete()
    return redirect('favoritos:index')
    #return redirect(reverse('favoritos:borrar', kwargs={'pk':pk}))


def detalle_favoritos(request, pk):
    favorito = Favoritos.objects.get(pk=pk)
    return render(request,'favoritos/detalle.html', context={'object':favorito})


def actualizar_favoritos(request, pk):
    favorito = Favoritos.objects.get(pk=pk)
    # form = FavoritoForm()
    form = FavoritoModelForm(instance=favorito)

    if request.method == 'POST':
        form = FavoritoModelForm(request.POST, instance=favorito)

        if form.is_valid():
            form.save()
        else:
            print(form.errors)
        
        #print(request.POST)
        #nombre = request.POST['nombre']
        #url = request.POST['url']
       # form = FavoritoForm(request.POST)
        #if form.is_valid():
       #     nombre = form.cleaned_data['nombre']
       #     url = form.cleaned_data['url']
      #      Favoritos.objects.create(nombre=nombre, url=url)
       # else:
       #     print(form.errors)
        #favorito = Favoritos()
        #favorito.nombre = nombre
        #favorito.url = url
        #favorito.save()

    context = {
        'form':form,
        'titulo':'Actualizar favorito'
    }
    return render(request, 'favoritos/crear.html', context)

django13/favoritos/templates/favoritos/crear.html
{% extends 'base_bs5.html' %}

{% block container %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1>{{ titulo }}</h1>
      <p><a href="{% url 'favoritos:index' %}">Atras</a></p>
    
      <form method='post'>
        {% csrf_token %}
    
        <table class="table">
          {{ form.as_table }}
        </table>
        <input type="submit" class="btn btn-outline-primary">
    
        <!--<label>Nombre</label>
        <input type="text" name = 'nombre'>
        <label>url</label>
        <input type="text" name='url'>
        <input type="submit">
        --->
      </form>
    </div>
  </div>
</div>


{% endblock container %}

django13/favoritos/templates/favoritos/detalle.html
{% extends 'base_bs5.html' %}

{% block container %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>detalle favorito</h1>
            <p><a href="{% url 'favoritos:index' %}">Atras</a></p>

            <p>{{ object.nombre }}</p>
            <p><a href="{{ object.url }}">{{ object.url }}</a></p>
        </div>
    </div>
</div>

  
{% endblock container %}

django13/favoritos/templates/favoritos/lista.html
{% extends 'base_bs5.html' %}

{% block container %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1> Favoritos</h1>
            <p>
                <a href="{% url 'favoritos:crear' %}" class="btn btn-outline-primary">
                >NUEVO
                </a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Url</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {%for favorito in favoritos_lista %}
                    <tr>
                        <td>{{ favorito.nombre }}</td>
                        <td>{{ favorito.url}}</td>
                        <td>
                            <a href="{% url 'favoritos:borrar' favorito.pk  %}" class="btn btn-outline-danger mb-2">Borrar</a>
                            <br>
                            <a href="{% url 'favoritos:detalle' favorito.pk  %}" class="btn btn-outline-info mb-2">Detalle</a>
                            <br>
                            <a href="{% url 'favoritos:actualizar' favorito.pk  %}" class="btn btn-outline-primary mb-2">Actualizar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock container %}

django13/templates/base_bs5.html
{% load static %}

<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FAVORITOS</title>
    <link href="{% static 'bs532/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
  </head>
  <body>
    {% block container %}
    {% endblock %}

    <script src="{% static 'bs532/js/bootstrap.bundle.min.js' %}"></script>
    {% block extra_js %}
    {% endblock %}
  </body>
</html>

django13/templates/index.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <title>HTML</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        </head>
        
     <body>
        <p> favoritos </p>
    </body>
</html>